# NUMPY

### for numerical python

### mean and average and other mahtematucal in data 

### It is similiear ot list but it can operate easily on large data  and have effiecient strage

### IT is very efficient as the data grows larger in size 

In [7]:
import numpy as np
numpy.__version__
np.__version__

'1.26.4'

### CREATING AN ARRAY FROM LISTS

In [12]:
my_arr=np.array([1,2,4,4,5])
print(my_arr)
print(type(my_arr))
#nd is nth dimensional 



['1' '2' 'a' '4' '5']
<class 'numpy.ndarray'>


### Using many data types are not preferred

In [14]:
#if we use many data types it changes all the member to higher data types implicitly
new=[1,2,'a','b']
new_array=np.array(new)
print((new_array))


['1' '2' 'a' 'b']


In [16]:
#dtype U32 is considered as string which is usde in dtype='U32'
#


### Changing the datatype from the keyword dtype

In [28]:
n=np.array([1,3.33,4.44,3],dtype='float16')
print(n)
n=np.array([1,3.33,4.44,3],dtype='U32')
print(n)

[1.   3.33 4.44 3.  ]
['1' '3.33' '4.44' '3']


In [ ]:
#

In [27]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### CREATING AN ARRAY OF ZEROS WITH LENGTH

In [29]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

### CREATING THIRD DIMENSIONAL ARRAY WITH ONES

In [30]:
np.ones((3,5),dtype=float)#syntax np.num((rows,column),dtype=datatype))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Only zero and one are in the library to use

### Making an array to use range of array from 1 to 30

In [34]:
np.arange(1,21,2)#arange=range of array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

### Linspace() -Helps to divide certain digits into parts

In [35]:
np.linspace(1,5,5)#(start,end(included),parts)

array([1., 2., 3., 4., 5.])

In [37]:
np.random.random((3,3))#it choosses an array of random digits from 0 to 1 in rows3 and column 3

array([[0.09370012, 0.71925163, 0.58282652],
       [0.74559702, 0.69492279, 0.16278081],
       [0.98972831, 0.22940795, 0.72949991]])

In [38]:
np.random.random((1,3))

array([[0.74375854, 0.2660427 , 0.9010402 ]])

### Normal distribution:symetrical graph 

In [40]:
np.random.normal(0,1,(3,3))

array([[ 1.32851358,  0.12594966, -0.63586182],
       [-0.81974854,  0.91750694, -1.18087439],
       [ 1.14915537,  0.73367328,  1.09481731]])

### RAMDOM WITH INTEGER AND RANGE

In [41]:
np.random.randint(0,10,(3,3))#10 exclusive

array([[6, 8, 6],
       [1, 9, 4],
       [1, 4, 6]])

In [45]:
np.random.randint(1,20,(2,4))

array([[11,  1, 11, 14],
       [16, 15,  5,  5]])

### Identity or symmetrical matrix

In [46]:
np.eye(4)#both row and column sizes are same and arguement is for both row and xolumn

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
np.empty(10)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 3.33772792e-307,
       6.23047503e-307, 2.22526399e-307, 6.23053614e-307, 7.56592338e-307,
       9.34588061e-307, 3.62651150e-317])

# NUMPY DATATYPE

### TRY TO SEPERATE INT8 INT16 INT32 AND OTHERS
uint for unsigned 
float_ for float
complex_ for complex number

### two dimensional is mostly used

### seed is used on the top of the random to ensure the value does not change

In [80]:
np.random.seed(0)
np.random.random((4,4))


array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [84]:
x=np.random.randint(1,10,size=5)
print(x)

[4 4 8 1 2]
